version: '3.9'

services:
  db-master:
    container_name: db-master
    hostname: db-master
    image: mysql:debian
    restart: unless-stopped
    tty: true
    stdin_open: true
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - ./config/master.cnf:/etc/mysql/my.cnf:ro
      - ./sql/master/replication_user.sql:/docker-entrypoint-initdb.d/replication_user.sql:ro
      - ./sql/master/scheme.sql:/docker-entrypoint-initdb.d/scheme.sql:ro
      - ./sql/master/values.sql:/docker-entrypoint-initdb.d/values.sql:ro
    mem_limit: 512M
    networks:
      macvlan:
        ipv4_address: 192.168.120.21


  db-slave-1:
    container_name: db-slave-1
    hostname: db-slave-1
    image: mysql:debian
    restart: unless-stopped
    tty: true
    stdin_open: true
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - ./config/slave.cnf:/etc/mysql/my.cnf:ro
      - ./sql/slave:/docker-entrypoint-initdb.d:ro
    mem_limit: 512M
    networks:
      macvlan:
        ipv4_address: 192.168.120.22

  db-slave-2:
    container_name: db-slave-2
    hostname: db-slave-2
    image: mysql:debian
    restart: unless-stopped
    tty: true
    stdin_open: true
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - ./config/slave.cnf:/etc/mysql/my.cnf:ro
      - ./sql/slave:/docker-entrypoint-initdb.d:ro
    mem_limit: 512M
    networks:
      macvlan:
        ipv4_address: 192.168.120.23
  
networks:
  macvlan:
    name: macvlan
    driver: macvlan
    driver_opts:
      parent: ens33
    ipam:
      config:
        - subnet: 192.168.120.0/24
          gateway: 192.168.120.1